### ISSUE TITLE
Use @ sign instead of np.dot in modeling labs?

### ISSUE THREAD

**Issue by charlesfrye** [charlesfrye/AppliedStatisticsForNeuroscience#34]
For consistency's sake, this might require changing the interactive model code, which would be a pain.

**Comment by choldgraf** [comment]
Don't forget this won't work outside of 3.6, which might cause confusion

**Comment by charlesfrye** [comment]
Hey Chris! Didn't realize anyone was listening on here!

You make a fair point! FYI @ was added in 3.5, not 3.6 though.

I recently bumped the required environment to 3.6, since it seems like newer versions of some packages are starting to drop support for 3.4. The version I'm writing now is also supposed to last through mid-2019, so I'm already aiming for two years of future-proof-ness.

I think I can afford to be a little strict on the environment -- I'm expecting my users to be either 1) installing Python according to my instructions or 2) in a Binder-based environment I get to dictate.

**Comment by choldgraf** [comment]
haha - yep, I am solidly lurking here ;-)

from a requirements standpoint, I totally agree with you. I've found that sometimes introducing syntax that only lives in specific python versions is more of a confusion for people that may ultimately interact with other python environments (e.g., if they're doing work that requires python 2.x, they may assume that @ is available to them when it's not).

either way the choice is yours - I can see good arguments for it in either case, just giving my lurky 2 cents :-)

**Comment by charlesfrye** [comment]
Ahhh I get you. That's a very good point!
