### ISSUE TITLE
01 Lab A

### ISSUE THREAD

**Issue by dmazin** [charlesfrye/AppliedStatisticsForNeuroscience#40]
- In "## What are Probability Distributions?" you list 3 common sense ideas that define distributions, but it's not clear whether these are THE assumptions of a distribution or just some of them.
- The intuitive explanation for mass functions in "### Probability Mass Functions" could also apply to density functions which confused me, doesn't make it clear that mass functions are discrete
- In "### Probability Density Functions" the alternating references to density fns and probability density fns confused me

**Comment by charlesfrye** [comment]
> In "## What are Probability Distributions?" you list 3 common sense ideas that define distributions, but it's not clear whether these are THE assumptions of a distribution or just some of them.

Since we're not actually going to prove anything rigorously in this course, I decided to leave that ambiguous. Those ideas are sufficient to define measures, many of which give rise to distributions, but only modulo some technical conditions. The way I've phrased it lets me be technically correct without being complete, which should only be noticed by folks with a more mathematical background. Possibly frustrating for them, but the audience is more scientists than mathematicians.

**Comment by charlesfrye** [comment]
> The intuitive explanation for mass functions in "### Probability Mass Functions" could also apply to density functions which confused me, doesn't make it clear that mass functions are discrete

That's a good point. I was hoping that focusing on implementations with lists and dicts would emphasize the discrete nature of pmfs, but perhaps that's not enough. It's just a bit tougher to motivate pmfs with a physical example, since they arise as abstractions of physical objects.

**Comment by charlesfrye** [comment]
> In "### Probability Density Functions" the alternating references to density fns and probability density fns confused me

There's an unfortunate collision of terms -- I'd like to call the non-probability density function a "mass density function", but then I'd have to call its counterpart a "mass mass function", which is not ideal. I went through and added the word "probability" at a few points to help disambiguate.

**Comment by charlesfrye** [comment]
One way to connect mass functions to a physical system is the function that assigns mass to a labeled set -- rocks in a box, for example.
