### ISSUE TITLE
in 00_setup / tutorial B

### ISSUE THREAD

**Issue by hungrstrike316** [charlesfrye/AppliedStatisticsForNeuroscience#41]
1. In **table of contents**, do you want to indent 1.2.1 & 1.2.2 further than 1.2?

2. In **from future import jetpack**, a typo seaborn is _visualization_

3. In **more python!**, link at bottom to pandas notebook is broken.

**Comment by charlesfrye** [comment]
1. That's fairly sensible, but I'd have to muck about with HTML formatting to change that, and I'm not feeling it.
1. willfix
1. willfix
