### ISSUE TITLE
In ANOVA I by Hand tutorial

### ISSUE THREAD

**Issue by hungrstrike316** [charlesfrye/AppliedStatisticsForNeuroscience#43]
In **Computing Mean Squares**, under the _mean_square_ compute cell, you say "how much different the groups" and I think it sounds better "how different" or "how much the groups differ"

**Comment by hungrstrike316** [comment]
Oh , in the paragraph just below this. You say "small squared error, aka small variance within groups, have high variance between groups," .  I think it sounds better using "large" variance between since u use "small" for the others.

**Comment by charlesfrye** [comment]
Good points!
