### ISSUE TITLE
In ANOVA II, by hand,

### ISSUE THREAD

**Issue by hungrstrike316** [charlesfrye/AppliedStatisticsForNeuroscience#47]
(1). You have the same paragraph twice under "Extending ANOVA to multiple variables"

(2). In "Two Way ANOVA", the 1st equation cell box, the equation goes off the right side (too long) in my browser.

(3).  In the "loading the data" section,  just under where it says "Compare the above Python expression to the mathematical expression below and make sure you can match up terms", I feel like this equation "ϵijk=Yijk−Ai−Bj−ABij" is missing the grand mean?  Also, you might could use more headers or sections?

**Comment by charlesfrye** [comment]
1. willfix
1. The intent was for that to be scrolled across. I've reduced the font size so that that isn't necessary. Trying to make the equations multiple lines requires some gnarly LaTeX formatting that I'm not tryna mess with.
1. Nicely spotted. And I agree, that's an oversight.
