### ISSUE TITLE
IN sampling and bootstrapping tutorial A

### ISSUE THREAD

**Issue by hungrstrike316** [charlesfrye/AppliedStatisticsForNeuroscience#48]
(1). Under "estimating sample distribution, I don't understand this. They are the same: 

"Note that both variables are actually functions, so we write
sampler = np.random.standard_normal
rather than
sampler = np.random.standard_normal"

(2). In "visualizing bootstrapping w histograms", you use this plot_bootstrap function, but it gives an error.  Is that something you meant to define or a library you meant to include?

**Comment by charlesfrye** [comment]
1. D'oh! That should be `sampler = np.random.standard_normal()`. I've added more text to make that section clearer.
1. Yeah, that section got messed up when I transitioned from functions inside the Jupyter notebook to functions in the `utils`.
